language: objective-c
osx_image: xcode8.3
sudo: false

script:
  - set -o pipefail && xcodebuild clean test
    -project FastcampusFrame.xcodeproj
    -scheme FastcampusFrame
    -sdk iphonesimulator10.3
    -destination "platform=iOS Simulator,OS=10.3,name=iPhone 7"
